import Head from 'next/head'
import Navbar from './components/navbar'
import  Features from "./components/Features"
import { useRouter } from "next/router";

// import About from "./components/About"
export default function Home() {
  const router = useRouter();

  const redirect = () =>{
   
    router.push('login');
 
  }
  return (
    <>
      <Head>
        <title>PolyTix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>
        <a href="./login" className="text-[#000]">Login</a>
      </div> */}
      
      
      
    <div>
      <Navbar/>
      <div className="relative h-screen">
            {/* <div className="absolute inset-0">
                <img className='bg-cover'
                    src="/images/matic_bg.jpg"
                    alt="background image"
                />
            </div> */}
            <div className="relative z-10 flex flex-col items-center justify-center h-full bg-black">
                <img src='/images/hero.png' className='px-10 pb-16'/>
                <div className='absolute pl-20 w-full'>
                  <button onClick={redirect} className='ml-72 p-5 mt-16 text-lg text-white hover:text-black hover:bg-white font-main bg-black px-9 py-4 shadow-lg shadow-gray-800 rounded-full font-bold my-3 hover:shadow-xl active:scale-90 transition duration-150'>TRY NOW!</button>
                </div>
            </div>
        </div>
        {/* <About /> */}
        <Features />


    <div>
        <div className='grid grid-cols-1 md:grid-cols-3 gap-y-10 px-10 p-10 justify-items-center py-14 bg-gray-900 text-white'>
        <div className='space-y-4 text-gray 800'>
            <h5 className='font-bold text-md'>Our Hackathon Project</h5>
            <p className='text-[#C754A7] font-bold text-5xl'>PolyTix</p>
        </div>
        <div className='space-y-4 text-md text-gray 800'>
            <h5 className='font-bold text-md'>Our Team</h5>
            <p>Byte Busters</p>
        </div>
        <div className='space-y-4 text-md text-gray 800'>
            <h5 className='font-bold text-md'>Team Members</h5>
            <p>Tanishka Borkar</p>
            <p>Nidhi Bhanushali</p>
            <p>Meet Dama</p>
            <p>Avisha Shah</p>
        </div>
        
    </div>
    </div>




    </div>
    
  
  
  
    </>
  )
}

// import Image from 'next/image'
// import { useRouter } from "next/router";
// import { Inter } from 'next/font/google'
// import Navbar from '../components/Navbar'
// import About from '../components/About'
// import Feature from '../components/Features'
// import Features from '../components/Features'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {

//   const router = useRouter();

//   const redirect = () =>{

//     router.push('login');

//   }
//   return (
//     <div>
//       <Navbar/>
      // <div className="relative h-screen">
      //       {/* <div className="absolute inset-0">
      //           <img className='bg-cover'
      //               src="/images/matic_bg.jpg"
      //               alt="background image"
      //           />
      //       </div> */}
      //       <div className="relative z-10 flex flex-col items-center justify-center h-full bg-black">
      //           <img src='/images/hero.png' className='px-10 pb-16'/>
      //           <div className='absolute top-1/2 w-full'>
      //             <button onClick={redirect} className='ml-72 mt-16 text-lg text-white font-main bg-black px-9 py-4 shadow-lg shadow-gray-800 rounded-full font-bold my-3 hover:shadow-xl active:scale-90 transition duration-150'>TRY NOW!</button>
      //           </div>
      //       </div>
      //   </div>
//         <About />
//         <Features />
//     </div>
    
//   )
// }